### PR TITLE
Placholderimg

### PR DESCRIPTION
**Pull request by Saga-sanga**
# Description

When creating a new product without an image, there are broken images showing up in the product catalog. I have fixed this by adding a default value to the `src` image with `placeholder.png`.

Screenshot 2022-09-25 135338
Screenshot 2022-09-25 135448

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks Saga-sanga, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - Looks like you run npm install, but we're using yarn. Please remove "frontend/package-lock.json" from your PR and use yarn instead.

**Comment by Saga-sanga** [comment]
> Some issues need to be fixed before you can merge your PR:
> 
> * Looks like you run npm install, but we're using yarn. Please remove "frontend/package-lock.json" from your PR and use yarn instead.

Alright! On it!

**Review by vanessa-cooper — APPROVED** [review]
Excellent job Saga-sanga! You're now able to merge the PR.

**Pull request merged**
